with seed as (
  select *
  from jsonb_to_recordset($json$
[
  {
    "product": "Toniiq Muscle Peptides",
    "queue": "Active Development",
    "state": "Spec Complete",
    "priority": "high",
    "lv_score": 83,
    "lv_score_note": null,
    "lv_band": "Attack Now",
    "confidence": "High",
    "last_updated": "2026-05-11",
    "today_action": "Sean Wells follow-up; Nuritas hold note; NBC boron spec; check DL185 sample eval",
    "decision_needed": "Proceed to AUDIT after boron spec + sample eval?",
    "blocker_risk": "Sean advisory close; boron elemental ratio; compliance copy",
    "reactivation_trigger": null,
    "local_folder_path": "Product Development/Dileucine Muscle Complex/",
    "concept_id": "dbad2905-83f4-412a-b60d-b8550511d16f",
    "registry_anchor": "#toniiq-muscle-peptides",
    "sort_order": 1
  },
  {
    "product": "Iodine Nasal Spray",
    "queue": "Active Development",
    "state": "Sourcing",
    "priority": "medium",
    "lv_score": 85,
    "lv_score_note": null,
    "lv_band": "Attack Now",
    "confidence": "Med",
    "last_updated": "2026-04-13",
    "today_action": "Await/chase Mimi; resolve BAC vs potassium sorbate, black bottle, bench samples",
    "decision_needed": "Is nasal-spray execution risk acceptable if Herbally Yours confirms bench samples?",
    "blocker_risk": "Sterility/preservative + new format + nasal-spray packaging",
    "reactivation_trigger": null,
    "local_folder_path": "Product Development/Iodine Nasal Spray/",
    "concept_id": null,
    "registry_anchor": "#iodine-nasal-spray",
    "sort_order": 2
  },
  {
    "product": "Neuropathy Support Complex",
    "queue": "Active Development",
    "state": "Spec Complete",
    "priority": "medium",
    "lv_score": 84,
    "lv_score_note": null,
    "lv_band": "Attack Now",
    "confidence": "High",
    "last_updated": "2026-05-11",
    "today_action": "Await samples from Phytochem (benfotiamine+ALCAR) and Effepharm (PEA)",
    "decision_needed": "None - sample requests sent",
    "blocker_risk": "GDrive upload pending (manual)",
    "reactivation_trigger": null,
    "local_folder_path": "Product Development/Neuropathy Support Complex/",
    "concept_id": "ea4264bb-d660-4c53-b55a-d0a203e3f00e",
    "registry_anchor": "#neuropathy-support-complex",
    "sort_order": 3
  },
  {
    "product": "Nattokinase 5-in-1",
    "queue": "Active Development",
    "state": "R&D",
    "priority": "medium",
    "lv_score": 69,
    "lv_score_note": null,
    "lv_band": "Selective Hold",
    "confidence": "Med",
    "last_updated": "2026-04-22",
    "today_action": "Active R&D / top greenlight candidate: confirm Peptizyme sample status; resolve DRcaps/copacking/doc drift",
    "decision_needed": "Is 5-in-1 circulatory positioning strong enough for the complexity?",
    "blocker_risk": "Sample in transit; DRcaps/copacking question; doc drift",
    "reactivation_trigger": null,
    "local_folder_path": "Product Development/Nattokinase Serrapeptase 5in1/",
    "concept_id": "b8dd1a61-525c-483d-8357-d606ae864d37",
    "registry_anchor": "#nattokinase-5-in-1-circulatory-complex",
    "sort_order": 4
  },
  {
    "product": "Aged Garlic Extract",
    "queue": "Active Development",
    "state": "R&D",
    "priority": "medium",
    "lv_score": 64,
    "lv_score_note": null,
    "lv_band": "Selective Hold",
    "confidence": "Med",
    "last_updated": "2026-04-07",
    "today_action": "Active R&D / top greenlight candidate: confirm CimaSci sample + 1% SAC COA; ready current costings",
    "decision_needed": "Does AGE + CoQ10 have a strong enough Amazon wedge?",
    "blocker_risk": "Supporting docs/sample status need confirmation",
    "reactivation_trigger": null,
    "local_folder_path": "Product Development/Aged Garlic Extract/",
    "concept_id": "023500b6-5d57-4963-9ff9-b55a872ff525",
    "registry_anchor": "#aged-garlic-extract",
    "sort_order": 5
  },
  {
    "product": "Premium Quercetin (Quercefit® 5-in-1)",
    "queue": "Active Development",
    "state": "R&D",
    "priority": "high",
    "lv_score": 66,
    "lv_score_note": null,
    "lv_band": "Needs One Unlock",
    "confidence": "Med",
    "last_updated": "2026-05-11",
    "today_action": "Samples in flight from Indena (Quercefit) + Jiaherb (Bioflavonoids unstandardized RFQ + sample); Bromelain + Zinc on hand. Await Jason eval.",
    "decision_needed": "None - spec locked, samples requested, awaiting eval",
    "blocker_risk": "Sample arrival + Jason eval",
    "reactivation_trigger": null,
    "local_folder_path": "Product Development/Quercetin/",
    "concept_id": "b17bf40d-b58f-47b1-9dee-0b2af9dd8bef",
    "registry_anchor": "#premium-quercetin-quercefit-5-in-1",
    "sort_order": 6
  },
  {
    "product": "Nicotine Free Pouches",
    "queue": "Active Development",
    "state": "Concept/Research",
    "priority": "medium",
    "lv_score": 71,
    "lv_score_note": null,
    "lv_band": "Needs One Unlock",
    "confidence": "Med",
    "last_updated": "2026-04-09",
    "today_action": "Choose Focus vs Performance vs multi-line; contact Daily Manufacturing",
    "decision_needed": "Is Toniiq willing to enter a new pouch format/category?",
    "blocker_risk": "New format; CoMan dependency; MOQ; taste/pouch quality",
    "reactivation_trigger": null,
    "local_folder_path": "Product Development/Nicotine Free Pouches/",
    "concept_id": null,
    "registry_anchor": "#nicotine-free-pouches",
    "sort_order": 7
  },
  {
    "product": "Creatine Chews",
    "queue": "Active Development",
    "state": "Evaluation complete (Phase B done)",
    "priority": "high",
    "lv_score": 68,
    "lv_score_note": "Phase B complete; Econ/Exec pending",
    "lv_band": "Selective Hold",
    "confidence": "Med",
    "last_updated": "2026-05-10",
    "today_action": "Await CDMO replies (Catalent/Sirio/Vitaquest). Then run decide_greenlight pending_action d9c22de8 (economics gate).",
    "decision_needed": "Greenlight decision after CDMO economics are known (MOQ + unit cost + feasibility).",
    "blocker_risk": "CDMO unit economics unknown; form-factor feasibility at 5g/chew still needs CDMO confirmation.",
    "reactivation_trigger": null,
    "local_folder_path": "Product Development/Creatine Chews/",
    "concept_id": "e80df747-4843-45d7-ae76-e01cffd9d64e",
    "registry_anchor": "#creatine-chews",
    "sort_order": 8
  },
  {
    "product": "Creatine HMB for Men",
    "queue": "Active Development",
    "state": "Concept / initial formulation",
    "priority": "high",
    "lv_score": 71,
    "lv_score_note": "alt HMB quote pending",
    "lv_band": "Needs One Unlock",
    "confidence": "Med",
    "last_updated": "2026-05-12",
    "today_action": "Await ECA / EffePharm HMB replies; then draft costing and decide clean 2-active vs D3 version",
    "decision_needed": "Does HMB sourcing/economics support a true 3g serving?",
    "blocker_risk": "NNB quoted $22.89/kg Calcium HMB but no U.S. stock; ECA/EffePharm quote, MOQ, lead time, form, and sample availability pending",
    "reactivation_trigger": null,
    "local_folder_path": "Product Development/Creatine HMB for Men/",
    "concept_id": "e01b942e-9f15-4154-85eb-0deb15e183d7",
    "registry_anchor": "#creatine-hmb-for-men",
    "sort_order": 9
  },
  {
    "product": "Liposomal Iron",
    "queue": "Greenlight Bench",
    "state": "GL Candidate",
    "priority": "normal",
    "lv_score": 69,
    "lv_score_note": null,
    "lv_band": "Selective Hold",
    "confidence": "Med",
    "last_updated": "2026-04-06",
    "today_action": "Re-evaluate for greenlight only if women's-health slot is desired",
    "decision_needed": "Is this a launch priority vs stronger Attack Now products?",
    "blocker_risk": "Needs freshness check before greenlight",
    "reactivation_trigger": "Freshness check + decision on whether the slot is strategically worth using now",
    "local_folder_path": "Product Development/Liposomal Iron/",
    "concept_id": null,
    "registry_anchor": "#liposomal-iron",
    "sort_order": 1
  },
  {
    "product": "Citrus Bergamot",
    "queue": "Greenlight Bench",
    "state": "GL Candidate",
    "priority": "medium",
    "lv_score": 64,
    "lv_score_note": null,
    "lv_band": "Selective Hold",
    "confidence": "Med",
    "last_updated": "2026-04-06",
    "today_action": "Refresh greenlight-bench status; ensure latest v3 Artichoke costing is on GDrive",
    "decision_needed": "Is bergamot still worth a greenlight slot vs stronger cardiovascular concepts?",
    "blocker_risk": "Stale status; sample uncertainty",
    "reactivation_trigger": "Refresh sample/status and confirm whether v3 Artichoke costing is still the version to greenlight",
    "local_folder_path": "Product Development/Citrus Bergamot/",
    "concept_id": "279d3832-eb70-4c5f-a194-065b1fedb339",
    "registry_anchor": "#citrus-bergamot",
    "sort_order": 2
  },
  {
    "product": "Lactoferrin",
    "queue": "Greenlight Bench",
    "state": "GL Candidate",
    "priority": "normal",
    "lv_score": 53,
    "lv_score_note": null,
    "lv_band": "Park / Reframe",
    "confidence": "Med",
    "last_updated": "2026-05-12",
    "today_action": "Freshness check only: confirm zinc form, colostrum spec, Amazon commission, and sharpen the Amazon hook",
    "decision_needed": "Is Lactoferrin Complex compelling enough to use a greenlight slot after standalone economics failed?",
    "blocker_risk": "COGS/price pressure; unclear Amazon hook",
    "reactivation_trigger": "Confirm zinc form, colostrum 30% IgG spec, Amazon commission, and whether the complex has a sharper Amazon hook",
    "local_folder_path": "Product Development/Lactoferrin/",
    "concept_id": null,
    "registry_anchor": "#lactoferrin",
    "sort_order": 3
  },
  {
    "product": "Colostrum Capsules",
    "queue": "Greenlight Bench",
    "state": "GL Candidate",
    "priority": "normal",
    "lv_score": 51,
    "lv_score_note": null,
    "lv_band": "Park / Reframe",
    "confidence": "Med",
    "last_updated": "2026-04-06",
    "today_action": "Do NOT greenlight without a fresh postmortem on weak 50% IgG launch",
    "decision_needed": "Why would this version win when 50% IgG had weak results?",
    "blocker_risk": "Prior weak launch result",
    "reactivation_trigger": "Do not greenlight without a fresh postmortem on weak 50% IgG launch",
    "local_folder_path": "Product Development/Colostrum Capsules/",
    "concept_id": null,
    "registry_anchor": "#colostrum-capsules",
    "sort_order": 4
  },
  {
    "product": "Liposomal Senolytic Complex",
    "queue": "Selective Hold",
    "state": "R&D",
    "priority": "high",
    "lv_score": 60,
    "lv_score_note": null,
    "lv_band": "Selective Hold",
    "confidence": "Med",
    "last_updated": "2026-05-03",
    "today_action": "Cheap feasibility checks only; do not spend more until Amazon attackability is proven",
    "decision_needed": "Before more spend: is this Amazon-attackable or mainly science-clever?",
    "blocker_risk": "Quote freshness; copacking quote; niche demand clarity",
    "reactivation_trigger": "Sample/quote/copacker checks materially improve the launch case",
    "local_folder_path": "Product Development/Liposomal Fisetin Quercetin/",
    "concept_id": "9b494668-844b-4d27-a99b-32d332994042",
    "registry_anchor": "#liposomal-senolytic-complex",
    "sort_order": 1
  },
  {
    "product": "PHGG / Sunfiber",
    "queue": "Shelved / Parked",
    "state": "Shelved",
    "priority": "parked",
    "lv_score": 67,
    "lv_score_note": null,
    "lv_band": "Park / Reframe",
    "confidence": "Med",
    "last_updated": "2026-05-11",
    "today_action": "No active work; preserve PHGG/Fibalance research for future fiber revisit",
    "decision_needed": "Can Fibalance PHGG win without the Sunfiber branded-search moat?",
    "blocker_risk": "Sunfiber unavailable for 2026; Fibalance lacks consumer brand pull; no clean wedge",
    "reactivation_trigger": "Sunfiber supply reopens, or a Fibalance-based concept proves a non-Sunfiber Amazon wedge",
    "local_folder_path": "Product Development/PHGG/",
    "concept_id": "fb5568e5-a348-4e19-8cf8-a112c121513f",
    "registry_anchor": "#phgg-sunfiber",
    "sort_order": 1
  },
  {
    "product": "GLP1 Fiber",
    "queue": "Shelved / Parked",
    "state": "Shelved",
    "priority": "parked",
    "lv_score": 61,
    "lv_score_note": null,
    "lv_band": "Park / Reframe",
    "confidence": "Med",
    "last_updated": "2026-05-11",
    "today_action": "No active work; preserve GLP-1 Fiber + Fiber Complete work as archived fiber research",
    "decision_needed": "Should Fiber Complete ever be funded as a deliberate broad-category entry bet?",
    "blocker_risk": "Exact GLP-1 fiber search demand is tiny; Fiber Complete requires tough broad-keyword launch",
    "reactivation_trigger": "A clearly attackable subcategory appears, or Toniiq chooses to fund Fiber Complete as a deliberate category-entry bet",
    "local_folder_path": "Product Development/GLP1 Fiber/",
    "concept_id": "2713f502-f4f4-47ef-a3d4-abd9408546dc",
    "registry_anchor": "#glp1-fiber",
    "sort_order": 2
  },
  {
    "product": "Protein Coffee",
    "queue": "Shelved / Parked",
    "state": "Shelved",
    "priority": "parked",
    "lv_score": 49,
    "lv_score_note": null,
    "lv_band": "Park / Reframe",
    "confidence": "High",
    "last_updated": "2026-05-01",
    "today_action": "No active work. Revisit only if supplier capacity/flavor/economics change",
    "decision_needed": "None now - conditions to revisit are explicit",
    "blocker_risk": "Economics + supply chain currently broken",
    "reactivation_trigger": "Supplier capacity opens, flavor-viable base emerges, verified QC supplier appears, and economics rework clears",
    "local_folder_path": "Product Development/Protein Coffee/",
    "concept_id": "ebfd98e2-7616-427a-bc4a-ba81c1c338fd",
    "registry_anchor": "#protein-coffee--shelved",
    "sort_order": 3
  },
  {
    "product": "Beet Root Capsules",
    "queue": "Shelved / Parked",
    "state": "On Hold",
    "priority": "parked",
    "lv_score": 59,
    "lv_score_note": null,
    "lv_band": "Park / Reframe",
    "confidence": "Med",
    "last_updated": "2026-04-14",
    "today_action": "No active work unless Udae feedback creates a sharper angle",
    "decision_needed": "Is there a differentiated Amazon wedge beyond nitric oxide/beet commodity?",
    "blocker_risk": "Parked by Gautam",
    "reactivation_trigger": "Udae feedback or a sharper nitric-oxide/beet angle changes conviction",
    "local_folder_path": "Product Development/Beet Root Capsules/",
    "concept_id": "791ea46c-6087-446c-9762-93f7636506f6",
    "registry_anchor": "#beet-root-capsules",
    "sort_order": 4
  },
  {
    "product": "Lions Mane Triple Extract",
    "queue": "Shelved / Parked",
    "state": "Sourcing",
    "priority": "medium",
    "lv_score": 56,
    "lv_score_note": null,
    "lv_band": "Park / Reframe",
    "confidence": "Med",
    "last_updated": "2026-04-06",
    "today_action": "Only revisit if erysunanes or another defensible wedge becomes clear",
    "decision_needed": "Can Toniiq win in a highly competitive lion's mane category?",
    "blocker_risk": "Category competitiveness; low excitement",
    "reactivation_trigger": "Erysunanes or another defensible wedge becomes clear",
    "local_folder_path": "Product Development/Lions Mane Triple Extract/",
    "concept_id": "73243b5c-6531-4af5-a377-8c72bf8f6334",
    "registry_anchor": "#lions-mane-triple-extract",
    "sort_order": 5
  },
  {
    "product": "Mushroom Coffee Reformulation",
    "queue": "Shelved / Parked",
    "state": "Concept/Research",
    "priority": "medium",
    "lv_score": 50,
    "lv_score_note": null,
    "lv_band": "Park / Reframe",
    "confidence": "Low",
    "last_updated": "2026-04-21",
    "today_action": "Define what is changing vs current product only if reactivated",
    "decision_needed": "Is this a true relaunch opportunity or a maintenance reformulation?",
    "blocker_risk": "Scope undefined",
    "reactivation_trigger": "A clear reformulation thesis emerges",
    "local_folder_path": null,
    "concept_id": "a55658ad-3939-438b-825d-6788cad61840",
    "registry_anchor": "#mushroom-coffee-reformulation",
    "sort_order": 6
  },
  {
    "product": "NMN Collagen HA",
    "queue": "Shelved / Parked",
    "state": "On Hold",
    "priority": "parked",
    "lv_score": 41,
    "lv_score_note": null,
    "lv_band": "Kill / Backlog",
    "confidence": "Med",
    "last_updated": "2026-04-14",
    "today_action": "No active work",
    "decision_needed": "No clear Amazon or DTC marketing path",
    "blocker_risk": "Parked due to unclear market pathway",
    "reactivation_trigger": "A credible positioning pathway appears",
    "local_folder_path": "Product Development/NMN Collagen HA/",
    "concept_id": null,
    "registry_anchor": "#nmn-collagen-ha",
    "sort_order": 7
  },
  {
    "product": "NAC Ethyl Ester",
    "queue": "Idea Backlog",
    "state": "Concept/Research",
    "priority": "medium",
    "lv_score": 50,
    "lv_score_note": null,
    "lv_band": "Park / Reframe",
    "confidence": "Low",
    "last_updated": "2026-04-23",
    "today_action": "Run market + competitive analysis only if promoted",
    "decision_needed": "Is NAC ethyl ester actually searchable + compliant on Amazon?",
    "blocker_risk": "No files yet",
    "reactivation_trigger": "Promote only if market + compliance screen creates enough evidence for a scored product row",
    "local_folder_path": null,
    "concept_id": "89435066-4775-4c1c-94e1-8eb79ffd5df9",
    "registry_anchor": "#nac-ethyl-ester",
    "sort_order": 1
  },
  {
    "product": "Methylene Blue + NMN",
    "queue": "Idea Backlog",
    "state": "Concept/Research",
    "priority": "medium",
    "lv_score": 47,
    "lv_score_note": null,
    "lv_band": "Park / Reframe",
    "confidence": "Low",
    "last_updated": "2026-04-23",
    "today_action": "Do not spend serious time before regulatory + Amazon eligibility check",
    "decision_needed": "Can methylene blue be safely/compliantly launched as Amazon supplement?",
    "blocker_risk": "Regulatory/Amazon risk; no files",
    "reactivation_trigger": "Promote only after regulatory + Amazon eligibility risk is cleared enough to justify development",
    "local_folder_path": null,
    "concept_id": "6f8ed957-c0da-4ce5-8b4e-3b303d667c44",
    "registry_anchor": "#methylene-blue--nmn",
    "sort_order": 2
  },
  {
    "product": "BPC 157 + NMN",
    "queue": "Idea Backlog",
    "state": "On Hold",
    "priority": "parked",
    "lv_score": 42,
    "lv_score_note": null,
    "lv_band": "Kill / Backlog",
    "confidence": "Low",
    "last_updated": "2026-04-09",
    "today_action": "No active work",
    "decision_needed": "Regulatory category risk likely dominates",
    "blocker_risk": "No files; high compliance risk",
    "reactivation_trigger": "Promote only if compliance risk changes materially",
    "local_folder_path": null,
    "concept_id": null,
    "registry_anchor": "#bpc-157--nmn",
    "sort_order": 3
  },
  {
    "product": "Magnesium Sleep Powder",
    "queue": "Idea Backlog",
    "state": "On Hold",
    "priority": "parked",
    "lv_score": 42,
    "lv_score_note": null,
    "lv_band": "Kill / Backlog",
    "confidence": "Low",
    "last_updated": "2026-04-09",
    "today_action": "No active work",
    "decision_needed": "What wedge beats saturated sleep powder market?",
    "blocker_risk": "Empty folder; low conviction",
    "reactivation_trigger": "Promote only if a differentiated wedge beats the saturated sleep powder market",
    "local_folder_path": "Product Development/Magnesium Sleep Powder/",
    "concept_id": null,
    "registry_anchor": "#magnesium-sleep-powder",
    "sort_order": 4
  }
]
$json$::jsonb
  ) as row (
    product text,
    queue text,
    state text,
    priority text,
    lv_score numeric,
    lv_score_note text,
    lv_band text,
    confidence text,
    last_updated date,
    today_action text,
    decision_needed text,
    blocker_risk text,
    reactivation_trigger text,
    local_folder_path text,
    concept_id uuid,
    registry_anchor text,
    sort_order integer
  )
)
insert into public.npd_registry_products (
  product,
  queue,
  state,
  priority,
  lv_score,
  lv_score_note,
  lv_band,
  confidence,
  last_updated,
  today_action,
  decision_needed,
  blocker_risk,
  reactivation_trigger,
  local_folder_path,
  concept_id,
  registry_anchor,
  detail_markdown,
  sort_order
)
select
  product,
  queue,
  state,
  priority,
  lv_score,
  lv_score_note,
  lv_band,
  confidence,
  last_updated,
  today_action,
  decision_needed,
  blocker_risk,
  reactivation_trigger,
  local_folder_path,
  concept_id,
  registry_anchor,
  concat(
    '### ', product,
    E'\n- Queue: ', queue,
    E'\n- State: ', state,
    E'\n- Priority: ', priority,
    E'\n- LV: ', coalesce(lv_score::text, 'n/a'), case when lv_score_note is null then '' else concat(' [', lv_score_note, ']') end,
    E'\n- LV Band: ', coalesce(lv_band, 'n/a'),
    E'\n- Confidence: ', coalesce(confidence, 'n/a'),
    E'\n- Today Action: ', coalesce(today_action, 'n/a'),
    E'\n- Decision Needed: ', coalesce(decision_needed, 'n/a'),
    E'\n- Blocker / Risk: ', coalesce(blocker_risk, 'n/a'),
    E'\n- Reactivation Trigger: ', coalesce(reactivation_trigger, 'n/a')
  ),
  sort_order
from seed
on conflict (product) do update set
  queue = excluded.queue,
  state = excluded.state,
  priority = excluded.priority,
  lv_score = excluded.lv_score,
  lv_score_note = excluded.lv_score_note,
  lv_band = excluded.lv_band,
  confidence = excluded.confidence,
  last_updated = excluded.last_updated,
  today_action = excluded.today_action,
  decision_needed = excluded.decision_needed,
  blocker_risk = excluded.blocker_risk,
  reactivation_trigger = excluded.reactivation_trigger,
  local_folder_path = excluded.local_folder_path,
  concept_id = excluded.concept_id,
  registry_anchor = excluded.registry_anchor,
  detail_markdown = excluded.detail_markdown,
  sort_order = excluded.sort_order;
